name: Code Review

permissions:
  contents: read
  pull-requests: write

on:
  pull_request:
    types: [ opened, reopened, synchronize ]

jobs:
  code_review:
    runs-on: ubuntu-latest
    name: ChatGPT Code Review
    steps:
      - uses: anc95/ChatGPT-CodeReview@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          # optional
          LANGUAGE: Korean
          MODEL: gpt-4o-mini-2024-07-18 # https://platform.openai.com/docs/models
